from Models import *
from Generator import *
from Puzzle import *
from Models16 import *
from Generator16 import *
from Puzzle16 import *
from Models25 import *
from Generator25 import *
from Puzzle25 import *
